/* DO NOT EDIT THIS FILE - it is machine generated */
//++#include <jni.h>
/* Header for class Cris_AscrmLog */

#ifndef _Included_Cris_AscrmLog
#define _Included_Cris_AscrmLog
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Cris_AscrmLog
 * Method:    SetLogLevel
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_Cris_AscrmLog_SetLogLevel
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
