/* DO NOT EDIT THIS FILE - it is machine generated */
//#include <jni.h>
/* Header for class Cris_Security */

#ifndef _Included_Cris_Security
#define _Included_Cris_Security
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Cris_Security
 * Method:    SetupSecurityLogFile
 * Signature: (Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Cris_Security_SetupSecurityLogFile
  (JNIEnv *, jclass, jstring, jint, jstring, jstring);

/*
 * Class:     Cris_Security
 * Method:    ActivateSecurityPort
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Cris_Security_ActivateSecurityPort
  (JNIEnv *, jobject, jint);

/*
 * Class:     Cris_Security
 * Method:    DeActivateSecurityPort
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Cris_Security_DeActivateSecurityPort
  (JNIEnv *, jobject);

/*
 * Class:     Cris_Security
 * Method:    DisableAlarm
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_Cris_Security_DisableAlarm
  (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     Cris_Security
 * Method:    GetDoorStatus
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_Cris_Security_GetDoorStatus
  (JNIEnv *, jobject, jint);

/*
 * Class:     Cris_Security
 * Method:    GetUPSStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Cris_Security_GetUPSStatus
  (JNIEnv *, jobject);

/*
 * Class:     Cris_Security
 * Method:    GetBatteryStatus
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_Cris_Security_GetBatteryStatus
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
