/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Cris_SmartCard */

#ifndef _Included_Cris_SmartCard
#define _Included_Cris_SmartCard
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Cris_SmartCard
 * Method:    JniSetupSmartCardLogFile
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_Cris_SmartCard_JniSetupSmartCardLogFile
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring);

/*
 * Class:     Cris_SmartCard
 * Method:    JniGetLastError
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Cris_SmartCard_JniGetLastError
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring);

/*
 * Class:     Cris_SmartCard
 * Method:    GetCardBlockStatus
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Cris_SmartCard_GetCardBlockStatus
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring);

/*
 * Class:     Cris_SmartCard
 * Method:    CardBlockStatusRequest
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Cris_SmartCard_CardBlockStatusRequest
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring);

/*
 * Class:     Cris_SmartCard
 * Method:    MutekInitWithCardRetain
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Cris_SmartCard_MutekInitWithCardRetain
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring);

/*
 * Class:     Cris_SmartCard
 * Method:    MutekInitWithCardMoveInFront
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Cris_SmartCard_MutekInitWithCardMoveInFront
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring);

/*
 * Class:     Cris_SmartCard
 * Method:    MutekInitWithErrorCardBin
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Cris_SmartCard_MutekInitWithErrorCardBin
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring);

/*
 * Class:     Cris_SmartCard
 * Method:    JniConnectDevice
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_Cris_SmartCard_JniConnectDevice
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring, jint, jint, jint);

/*
 * Class:     Cris_SmartCard
 * Method:    JniDisConnectDevice
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Cris_SmartCard_JniDisConnectDevice
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring, jint);

/*
 * Class:     Cris_SmartCard
 * Method:    JniGetDeviceStatus
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;II)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Cris_SmartCard_JniGetDeviceStatus
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring, jint, jint);

/*
 * Class:     Cris_SmartCard
 * Method:    JniAcceptCard
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Cris_SmartCard_JniAcceptCard
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring, jint);

/*
 * Class:     Cris_SmartCard
 * Method:    JniCollectCard
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Cris_SmartCard_JniCollectCard
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring, jint);

/*
 * Class:     Cris_SmartCard
 * Method:    JniDisableCardAcceptance
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Cris_SmartCard_JniDisableCardAcceptance
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring, jint);

/*
 * Class:     Cris_SmartCard
 * Method:    JniDispenseCard
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Cris_SmartCard_JniDispenseCard
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring, jint);

/*
 * Class:     Cris_SmartCard
 * Method:    JniEnableCardAcceptance
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Cris_SmartCard_JniEnableCardAcceptance
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring, jint);

/*
 * Class:     Cris_SmartCard
 * Method:    JniIsCardInChannel
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Cris_SmartCard_JniIsCardInChannel
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring, jint);

/*
 * Class:     Cris_SmartCard
 * Method:    JniIsCardRemoved
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Cris_SmartCard_JniIsCardRemoved
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring, jint);

/*
 * Class:     Cris_SmartCard
 * Method:    JniRejectCard
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_Cris_SmartCard_JniRejectCard
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring, jint);

/*
 * Class:     Cris_SmartCard
 * Method:    JniReturnCard
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_Cris_SmartCard_JniReturnCard
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring, jint, jint);

/*
 * Class:     Cris_SmartCard
 * Method:    JniSAMSlotPowerOnOff
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;II)I
 */
JNIEXPORT jint JNICALL Java_Cris_SmartCard_JniSAMSlotPowerOnOff
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring, jint, jint);

/*
 * Class:     Cris_SmartCard
 * Method:    JniResetSAM
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;III)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Cris_SmartCard_JniResetSAM
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring, jint, jint, jint);

/*
 * Class:     Cris_SmartCard
 * Method:    JniActivateCard
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;III)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Cris_SmartCard_JniActivateCard
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring, jint, jint, jint);

/*
 * Class:     Cris_SmartCard
 * Method:    JniDeactivateCard
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;III)I
 */
JNIEXPORT jint JNICALL Java_Cris_SmartCard_JniDeactivateCard
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring, jint, jint, jint);

/*
 * Class:     Cris_SmartCard
 * Method:    JniXChangeAPDU
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;I[BII)[B
 */
JNIEXPORT jbyteArray JNICALL Java_Cris_SmartCard_JniXChangeAPDU
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring, jint, jbyteArray, jint, jint);

/*
 * Class:     Cris_SmartCard
 * Method:    JniisSAMEnable
 * Signature: (Ljava/lang/String;Ljava/lang/String;ILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_Cris_SmartCard_JniisSAMEnable
  (JNIEnv *, jobject, jstring, jstring, jint, jstring, jstring);

/*
 * Class:     Cris_SmartCard
 * Method:    WriteNativeLog
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_Cris_SmartCard_WriteNativeLog
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
